# coding: utf-8

#
# vagrant-conoha
#
# プラグインの設定を行います。おもにConoHa APIに関するものです。
# コントロールパネルの「API」ページに必要情報があります。
# https://manage.conoha.jp/API/
#

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # このプラグインではConoHa(OpenStack)のイメージを使用するため、boxは利用できません。
  # このパラメータを変更する必要はありません。
  config.vm.box       = 'conoha'

  # vagrantがSSH接続する際のユーザ名を指定します。
  config.ssh.username = 'root'

  # CentOS系など/etc/sudoersにrequirettyが書いてある場合に必要になります。
  config.ssh.pty      = true

  config.vm.provider :conoha do |conoha|

    # IdentityEndpointを指定します
    # 東京以外のリージョンを利用する場合は変更して下さい。
    conoha.openstack_auth_url = 'https://identity.tyo1.conoha.io/v2.0'

    # APIユーザ名、APIパスワード、テナント名を指定します。
    # APIユーザー名はgncu、テナント名はgnctなので注意して下さい。
    conoha.username           = 'gncu*******'
    conoha.password           = '***********'
    conoha.tenant_name        = 'gnct*******'

    # VPSのスペックを指定します(g-1gbの場合は1GBプランになります)。
    # 2015/08/27現在、以下のプランが利用可能です。
    #
    # g-1gb
    # g-2gb
    # g-4gb
    # g-8gb
    # g-16gb
    # g-32gb
    # g-64gb
    #
    # 最新のプラン一覧はvagrantのopenstackコマンドで取得できます。
    # 以下のコマンドを実行して下さい。
    #
    # $ vagrant openstack flavor-list
    #
    conoha.flavor             = 'g-1gb'

    # VPSのイメージを指定します。
    # 2015/08/27現在、以下のイメージが利用可能です。
    #
    # vmi-archlinux-x86_64
    # vmi-centos-6.6-i386
    # vmi-centos-6.6-x86_64
    # vmi-centos-6.7-i386
    # vmi-centos-6.7-x86_64
    # vmi-centos-7.1-x86_64
    # vmi-concrete5-centos-6.7
    # vmi-debian-7-amd64
    # vmi-debian-7-i386
    # vmi-debian-8-amd64
    # vmi-debian-8-i386
    # vmi-docker-1.7.1-ubuntu-14.04
    # vmi-drupal-7.36-centos-6.6
    # vmi-fedora-21-x86_64
    # vmi-fedora-22-x86_64
    # vmi-freebsd-10.1-x86_64
    # vmi-freebsd-10.1-zfs-x86_64
    # vmi-gitlab-7.9.1-centos-6.6
    # vmi-hadoop-2.6-master-centos-6.6
    # vmi-hadoop-2.6-slave-centos-6.6
    # vmi-hinemos-5.0-centos-7.1
    # vmi-jenkins-1.6-centos-6.6
    # vmi-lamp-centos-6.6
    # vmi-meanstack-centos-6.6
    # vmi-opensuse-13.2-x86_64
    # vmi-owncloud-8-centos-6.6
    # vmi-redmine-3.0-centos-6.6
    # vmi-ror-4.2-centos-6.6
    # vmi-scientificlinux-7.1-x86_64
    # vmi-ubuntu-12.04-amd64
    # vmi-ubuntu-12.04-i386
    # vmi-ubuntu-14.04-amd64
    # vmi-ubuntu-14.04-i386
    # vmi-wp-4.3-centos-6-6
    #
    # 最新のイメージ一覧は、vagrantのopenstackコマンドで取得できます。
    # 以下のコマンドを実行してください。
    #
    # $ vagrant openstack image-list
    #
    conoha.image              = 'vmi-ubuntu-14.04-amd64'

    # リージョンを指定します。
    # 東京(tyo1)、シンガポール(sin1)、アメリカ(sjc1)から指定して下さい。
    #
    # conoha.openstack_auth_urlも忘れずに変更して下さい。
    conoha.region             = "tyo1"

    # VPSのrootパスワードを設定します。
    #
    # 空文字の場合はパスワードは設定されません
    # その場合コンソールログインは不可になります(SSHの公開鍵認証はログイン可能)
    conoha.admin_pass         = ""

    # VPSのネームタグを指定します。
    # コントロールパネル上に表示される名前です。
    conoha.metadata           = {
      instance_name_tag: "vagrant_conoha"
    }

    # セキュリティグループを指定します。
    #
    # NOTE: 一度もコントロールパネルからVPSを作成したことがない場合、
    #       以下のセキュリティグループが無いためエラーになることがあります。
    #       その場合は、コントロールパネルからVPSを作成して、すぐ削除して
    #       その後、このプラグインを試して下さい。
    conoha.security_groups    = [
      "default",
      "gncs-ipv4-all",
      "gncs-ipv6-all"
    ]

    # SSH公開鍵を指定します。
    # コントロールパネルの「SSH Key」にある名前を指定して下さい。
    # config.ssh.private_key_pathもともに指定する必要があります。
    #
    # 指定が無い場合は、Vagrantが新しい鍵ペアを自動作成します。
    #
    # conoha.keypair_name       = "my-keypair"

  end

  # すでにSSH公開鍵をコントロールパネルに登録している場合は、
  # ここで秘密鍵のパスを指定します。
  # keypair_nameとともに指定します。
  #
  # config.ssh.private_key_path = "~/.ssh/id_rsa"
end
